// <auto-generated />
using System;
using EmployeesApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeesApp.Migrations
{
    [DbContext(typeof(HrDatabaseContext))]
    [Migration("20240219211520_insert3Coloumns")]
    partial class insert3Coloumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeesApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeesId"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("EmployeesId");

                    b.ToTable("Employee", "dbo");

                    b.HasData(
                        new
                        {
                            EmployeesId = 1,
                            DOB = new DateTime(2024, 2, 19, 23, 15, 20, 473, DateTimeKind.Local).AddTicks(1979),
                            EmployeeName = "ahmed",
                            EmployeeNumber = "1001",
                            GrossSalary = 8000m,
                            HiringDate = new DateTime(2024, 2, 19, 23, 15, 20, 473, DateTimeKind.Local).AddTicks(2032),
                            NetSalary = 7000m
                        },
                        new
                        {
                            EmployeesId = 2,
                            DOB = new DateTime(2024, 2, 19, 23, 15, 20, 473, DateTimeKind.Local).AddTicks(2143),
                            EmployeeName = "hassan",
                            EmployeeNumber = "1002",
                            GrossSalary = 9000m,
                            HiringDate = new DateTime(2024, 2, 19, 23, 15, 20, 473, DateTimeKind.Local).AddTicks(2146),
                            NetSalary = 1000m
                        },
                        new
                        {
                            EmployeesId = 3,
                            DOB = new DateTime(2024, 2, 19, 23, 15, 20, 473, DateTimeKind.Local).AddTicks(2170),
                            EmployeeName = "ali",
                            EmployeeNumber = "1003",
                            GrossSalary = 11000m,
                            HiringDate = new DateTime(2024, 2, 19, 23, 15, 20, 473, DateTimeKind.Local).AddTicks(2172),
                            NetSalary = 12000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
